### ISSUE TITLE
Can not find remote branch %GTKTAG%.

### ISSUE THREAD

**Issue by FrankenApps** [MGlolenstine/gtk4-cross#4]
When I run `docker build gtk4-cross-base-hub -t gtk4-cross-base-hub` on the latest main, I get this error:

```
 => [stage-2  5/30] WORKDIR /tmp                                           0.0s
 => ERROR [stage-2  6/30] RUN git clone --depth 1 --branch %GTKTAG% https  1.9s
------
 > [stage-2  6/30] RUN git clone --depth 1 --branch %GTKTAG% https://gitlab.gnome.org/GNOME/gtk.git:
#21 0.489 Cloning into 'gtk'...
#21 1.844 warning: Could not find remote branch %GTKTAG% to clone.
#21 1.844 fatal: Remote branch %GTKTAG% not found in upstream origin
------
executor failed running [/bin/sh -c git clone --depth 1 --branch %GTKTAG% https://gitlab.gnome.org/GNOME/gtk.git]: exit code: 128
```

The culprint seems to be this commit: d0affccaca41c3e84b9dc87c6544d25c09de7db2 because when I check out this commit, the image is generated just fine.

**Comment by MGlolenstine** [comment]
Indeed.
I should update the README.md. 
Those tags are needed for the docker hub image generation.
If you want to manually build the images, replace %GTKTAG% with the latest gtk stable version `4.6.0` and %ADWTAG% with 1.0.1.
Otherwise you can lookup `mglolenstine/gtk4-cross` image on docker hub for a prebuilt image.
