### ISSUE TITLE
Icons missing in GTK File Chooser Dialogue

### ISSUE THREAD

**Issue by 13hannes11** [MGlolenstine/gtk4-cross#7]
I am not sure how the issue originates but in my application the GTK File Chooser Dialogue is slow and missing icons on the windows version packaged with this image.

**Comment by MGlolenstine** [comment]
Icons aren't packaged into the `package.zip` by default.
You will have to change the `package.sh` script to copy the theme you want included into the `package/` folder before you archive it.

`rust-crosscompile` does it like [this](https://github.com/etrombly/rust-crosscompile/blob/master/package.sh#L14-L36) for GTK3.
I was thinking about optimising it and never fully implemented it.
I'll take a look at porting the GTK3 code later today, if that's something you need.

`File Chooser Dialog` could be slow due to it missing icons.

**Comment by 13hannes11** [comment]
Do you think this could be added here and configured as an optional part of the script?

Alternatively a second script like `package_with_icons.sh` could be included to allow for that use case.

What do you think?

**Comment by MGlolenstine** [comment]
I would love to include the icons by default, as most of the programs make no sense when packaged without them.
However, I don't want to package 250MB (probably exaggerating) of icons and theme, if only a small portion of it is used.

I still need to think about it, but I do think splitting it into two different scripts would be a good option for now.

**Comment by 13hannes11** [comment]
I added the changes to try it out and the size of package.zip increased from ~15 mb to ~30 mb

**Comment by MGlolenstine** [comment]
You contribution is now present in the new containers.

Thank you!
(closing this as solved)
